#!/bin/sh

#comprovem que l'estat d'rigen sigui l'estat 3
if [ $(runlevel | cut -d ' ' -f1) -eq 5 ]
then
	#per tots els usuaris en la carpeta /home/:
	for user in $(more /etc/passwd | cut -d ":" -f1)
	do
		echo "S'executa el codi amb usuari $user" >> /home/milax/execucio.txt
		#comprovem que sigui un usuari 
		id $user > /dev/null >&2
		if [ $? -eq 0 ]
		then
			#comprovem que no hi hagi un backup del mateix dia de l'usuari
			if [ -e /back/$user/$(date +%y%m%d).tar.gz ]
			then
				#cas en que ja s'ha fet un backup aquest dia
				echo "Avui ja s'ha fet una copa de seguretat de l'usuari $user" >&2
			else
				if [ -d /back/$user ]
				then
					if [ $(ls -l /back/$user/ | wc -l) -gt 1 ]
					then
						#cas en que hi ha un backup d'un dia anterior
						#obtenim el nom de l'últim backup realitzat
						anterior=$(ls -l /back/$user/ | sed -n '2p' | cut -d ' ' -f9 )
						#comprimim aquells fitxers que s'han actualitzat des de l'últim backup
						find /home -user $user -newer /back/$user/$anterior > /tmp/new_files.txt
						tar -czf /back/$user/$(date +%y%m%d).tar.gz -T /tmp/new_files.txt
						chmod 700 /back/$user/$(date +%y%m%d).tar.gz
						chown $user:$user /back/$user/$(date +%y%m%d).tar.gz

					else
						find /home -user $user > /tmp/new_files.txt
						tar -czf /back/$user/$(date +%y%m%d).tar.gz -T /tmp/new_files.txt
					fi
				else
					#Cas en que no hi ha cap carpeta amb el nom de l'usuari
					mkdir -p /back/$user
					find /home -user $user > /tmp/new_files.txt
					tar -czf /back/$user/$(date +%y%m%d).tar.gz -T /tmp/new_files.txt
				fi
			fi
		fi
	done
fi
