#!/bin/bash
# Start/stop the backup service.
#
### BEGIN INIT INFO
# Provides:          backup
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:
# Should-Stop:       0,6
# Default-Start:	3
# Default-Stop:		0,6 
# Short-Description: Backup service program
# Description:		backup is a program that runs when the machine is shutted
#			down creating a compressed system backup for every user in
#			the system.
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="backup service"
NAME=backup
SCRIPTNAME=/etc/init.d/"$NAME"

backup_service(){
	echo "S'executa el codi $(date)" > /home/milax/execucio.txt
	echo "runlevel: $(runlevel)" >> /home/milax/execucio.txt
	#comprovem que l'estat d'origen sigui l'estat 3
	if [ $(runlevel | cut -d ' ' -f1) -eq 3 ]
	then
		#per tots els usuaris en la carpeta /home/:
		for user in $(ls /home)
		do
			#comprovem que sigui un usuari 
			id $user > /dev/null >&2
			if [ $? -eq 0 ]
			then
				#comprovem que no hi hagi un backup del mateix dia de l'usuari
				if [ -e /back/$user/$(date +%y%m%d).tar.gz ]
				then
					#cas en que ja s'ha fet un backup aquest dia
					echo "Avui ja s'ha fet una copa de seguretat de l'usuari $user" >&2
				else
					if [ -d /back/$user ]
					then
						if [ $(ls -l /back/$user/ | wc -l) -gt 1 ]
						then
							#cas en que hi ha un backup d'un dia anterior
							#obtenim el nom de l'últim backup realitzat
							anterior=$( ls -t /back/$user/ | sed -n '1p' )
							#comprimim aquells fitxers que s'han actualitzat des de l'últim backup
							find /home/$user -type f -user $user -newer /back/$user/$anterior > /tmp/new_files.txt
							tar -czf /back/$user/$(date +%y%m%d).tar.gz -T /tmp/new_files.txt
							chmod 700 /back/$user/$(date +%y%m%d).tar.gz
							chown $user:$user /back/$user/$(date +%y%m%d).tar.gz

						else
							#cas en que la carpeta amb el nom de l'usuari esta creada pero no hi ha cap backup
							find /home/$user -type f -user $user > /tmp/new_files.txt
							tar -czf /back/$user/$(date +%y%m%d).tar.gz -T /tmp/new_files.txt
							chmod 700 /back/$user/$(date +%y%m%d).tar.gz
							chown $user:$user /back/$user/$(date +%y%m%d).tar.gz
						fi
					else
						#Cas en que no hi ha cap carpeta amb el nom de l'usuari
						mkdir -p /back/$user
						find /home/$user -type f -user $user > /tmp/new_files.txt
						tar -czf /back/$user/$(date +%y%m%d).tar.gz -T /tmp/new_files.txt
						chmod 700 /back/$user/$(date +%y%m%d).tar.gz
						chown $user:$user /back/$user/$(date +%y%m%d).tar.gz
					fi
				fi
			fi
		done
	fi
}

case "$1" in
start)
        exit 0
	;;
stop)
        backup_service
        ;;
status)
        ;;
*)
        exit 2
        ;;
esac
exit 0
