#!/bin/bash

###############################################################################
# Autors: Cristòfol Daudèn, Aleix Marine i Josep Marín Llaó                                           
# Data d'implementació: 18/4/2018                                                   
# Versio 1.0                                                                        
# Permisos:						                                   
# Descripció i paràmetres: 
#
# Atrguments: Aquest script no necessita arguments ja que està pensat per a dur a terme
# un "override" de la comanda lp propia de sistemes Unix. 
#
# Simplement delega la trucada al programa lp sempre que la opció virtualImpre no estigui
# present en els arguments. Si hi és, demana la contrassenya de l'usuari. El programa
# verificar que la informació estigui correcte consultant la base de dades de passwords
# /usr/local/secret
###############################################################################

if [ "$(echo -e "$*" | grep -e "virtualImpre")" == "" ]
then # si no troba aquestes opcions
	$(whereis lp | cut -d ' ' -f2) $* #li passem la crida a la comanda real
else # si troba les opcions
	USER_NAME=$(whoami)
	# Comprovem existencia de directoris
	# considerem que el directori /usr/local ja existeixen
	if [ ! -f "/usr/local/secret" ]
	then # el fitxer de credencials no existeix
		echo -e "\nError, file /usr/local/secret does not exist"
		exit 1
	else # el fitxer de credencials existeix
		CREDENTIALS=$(more /usr/local/secret | openssl enc -aes-128-cbc -a -salt -pass pass: | grep "$USER_NAME")
		if [ -z "$CREDENTIALS" ]
		then # l'usuari actual no te credencials per utilitzar limpresora
			echo -e "\nError, you are not registered, so you cannot use virtualImpre\nAdd your credentials into /usr/local/secret and try again later"
			exit 2
		else # l'usuari te credencials
			echo -e "Introdueix la teva contrassenya"
			stty -echo # apaguem el echo
			read PASSWORD
			stty echo # l'encenem
			REAL_PASSWORD=$(echo $CREDENTIALS | cut -d ';' -f2)
			if [ "$REAL_PASSWORD" == "$PASSWORD" ]
			then # si el pass coincideix llavors cridem a la comanda
				$(whereis lp | cut -d ' ' -f2) $* #li passem la crida a la comanda real
			else # si no coincideix 
				echo -e "\nEl password no es correcte"
			fi
		fi
	fi
fi













