#!/bin/bash

<<INSTRUCCIONS
Es vol creat un script anomenat lp que supleixi lactual comanda lp (per a enviar a
imprimir un document) i que a mes de les opcions normals que accepta la comanda lp
estàndard, quan s’esculli la impressora virtualImpre, usant lopció -d de la comanda,
ens demani una paraula clau (emmaiatzemada per cada usuari), comprovi la validesa i
en cas que siiui correcta limprimeixi, si la clau es incorrecta, ha de donar un missatie
derror.
NOTA: El ftxer de paraules clau estarà en el directori /usr/local/secret i ha d’estar
format pel loiin i la paraula clau. Opcionalment les paraules clau shaurien dencriptar.
Heu de tenir en compte que la paraula clau no ha de sortir escrita per pantalla (heu
dusar la comanda stty per activar o desactivar lecho de pantalla)
INSTRUCCIONS

###############################################################################
# Autors: Cristòfol Daudèn, Aleix Marine i Josep Marín Llaó                                           
# Data d'implementació: 18/4/2018                                                   
# Versio 1.0                                                                        
# Permisos:	no cal root						                                   
# Descripció i paràmetres: Es vol implementar un script que posi a punt una comanda
# anomenada lp, que tingui les mateixes opcions que la comanda lp que ja es troba
# en el sistema pero que quan s'specifiqui el parametre -d acompanyat de virtualImpre
# sol·liciti una contrassenya (propia de cada usuari).
#
# L'script comprovara que la contrassenya introduida per l'usuari es la mateixa
# que esta definida per a aquell usuari en el fitxer /usr/local/secret.
# Si es correcta la comanda passa a executar-se, sinó mostra error.
# 
# Aquest fitxer tindra en cada linea el nom d'usuari i la seva contrassenya,
# separats per punt i coma:
#
# USER_NAME;PASSWORD
# 
# La constrassenya no sera mostrada per la pantalla.
#
# Aquest script no necessita arguments, excepte el d'ajuda que es opcional
###############################################################################

echo jelou9

if [ -z $(echo "$*" | grep -e -d virtualImpre) ]
then # si no troba aquestes opcions
	echo isreal
	$(whereis lp | cut -d ' ' -f2) $* #li passem la crida a la comanda real
else # si troba les opcions
	USER_NAME=$(whoami)
	echo "no hi son les opcions -d virtualImpre"
	# Comprovem existencia de directoris
	# considerem que el directori /usr/local ja existeixen
	if [ ! -f "/usr/local/secret" ]
	then # el fitxer de credencials no existeix
		echo -e "\nError, file /usr/local/secret does not exist. Creating..."
		touch /usr/local/secret
		echo -e "\nYou need to fill this file with passwords from users before executing the script"
		exit 1
	else # el fitxer de credencials existeix
		CREDENTIALS=$(more /usr/local/secret | grep "$USER_NAME")
		if [ -z $CREDENTIALS]
		then # l'usuari actual no te credencials per utilitzar limpresora
			echo -e "\nError, you are not registered, so you cannot use virtualImpre\nAdd your credentials into /usr/local/secret and try again later"
			exit 2
		else # l'usuari te credencials
			echo -e "\nIntrodueix la teva contrassenya"
			stty -echo # apaguem el echo
			read PASSWORD
			stty echo # l'encenem
			if [ $(echo $CREDENTIALS | cut -d ';' -f2) -eq $PASSWORD ]
			then # si el pass coincideix llavors cridem a la comanda
				$(whereis lp | cut -d ' ' -f2) $* #li passem la crida a la comanda real
			else # si no coincideix 
				echo -e "\nEl password no es correcte"
			fi
		fi
	fi
fi













